Snipamupdates
Keyfactor/citrix-adc-orchestrator pull request #4
Opened 2023-04-26 14:44 UTC by bhillkeyfactor

2023-04-26 14:45 UTC, bhillkeyfactor commented
Citrix Adc, Alias fixes, SNI Feature, Remove Nitro Source and Pam Support

2023-05-31 21:54 UTC, fiddlermikey requested changes
Please review and update the changelog and manfiest. Remove the runtest.bat file

2023-05-31 21:54 UTC, fiddlermikey commented on CHANGELOG.md
> +1.0.3
I do not believe we ever released a 1.0.3 and these updates appear to be for 2.0.0 and this should be updated.

2023-05-31 21:54 UTC, fiddlermikey commented on RunTest.bat
Should this file be removed? Is it an example? It contains a local user account for the first cd command

2023-05-31 21:54 UTC, fiddlermikey commented on integration-manifest.json
Universal Orchestrators now require kfutil definitions for cert store types in the manifest

2023-06-14 16:53 UTC, merged